name: bridge_cli
description: A sample command-line application.
version: 1.1.0

environment:
  sdk: ^3.10.7

dependencies:
  args: ^2.7.0
  path: ^1.9.0
  yaml: ^3.1.3
  watcher: ^1.2.1
  glob: ^2.1.3
  rxdart: ^0.28.0
  analyzer: ^10.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
